import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "~/styles/globals.css"
import { Providers } from "~/components/providers"
import { DictionaryContextProvider } from "~/store/language"
import { getDictionary } from "~/utils/dictonaries"

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: "normal",
  subsets: ["latin"],
  variable: "--font-inter",
})

export const metadata: Metadata = {
  title: "AuthKit",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const dictionary = await getDictionary()
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} bg-background min-h-screen w-full antialiased`}>
        <DictionaryContextProvider dictionary={dictionary}>
          <Providers>{children}</Providers>
        </DictionaryContextProvider>
      </body>
    </html>
  )
}
